//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 27.09.2013 15:21:45
namespace Ork.Employee.DomainModelService
{
    
    /// <summary>
    /// There are no comments for DomainModelContext in the schema.
    /// </summary>
    public partial class DomainModelContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new DomainModelContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DomainModelContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("OpenResKit.DomainModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("Ork.Employee.DomainModelService", typeName.Substring(22)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Ork.Employee.DomainModelService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("OpenResKit.DomainModel.", clientType.Name);
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for Appointments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Appointment> Appointments
        {
            get
            {
                if ((this._Appointments == null))
                {
                    this._Appointments = base.CreateQuery<Appointment>("Appointments");
                }
                return this._Appointments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Appointment> _Appointments;
        /// <summary>
        /// There are no comments for ResponsibleSubjects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ResponsibleSubject> ResponsibleSubjects
        {
            get
            {
                if ((this._ResponsibleSubjects == null))
                {
                    this._ResponsibleSubjects = base.CreateQuery<ResponsibleSubject>("ResponsibleSubjects");
                }
                return this._ResponsibleSubjects;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ResponsibleSubject> _ResponsibleSubjects;
        /// <summary>
        /// There are no comments for Series in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Series> Series
        {
            get
            {
                if ((this._Series == null))
                {
                    this._Series = base.CreateQuery<Series>("Series");
                }
                return this._Series;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Series> _Series;
        /// <summary>
        /// There are no comments for SeriesColors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SeriesColor> SeriesColors
        {
            get
            {
                if ((this._SeriesColors == null))
                {
                    this._SeriesColors = base.CreateQuery<SeriesColor>("SeriesColors");
                }
                return this._SeriesColors;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SeriesColor> _SeriesColors;
        /// <summary>
        /// There are no comments for DayOfWeeks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DayOfWeek> DayOfWeeks
        {
            get
            {
                if ((this._DayOfWeeks == null))
                {
                    this._DayOfWeeks = base.CreateQuery<DayOfWeek>("DayOfWeeks");
                }
                return this._DayOfWeeks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DayOfWeek> _DayOfWeeks;
        /// <summary>
        /// There are no comments for ScheduledTasks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ScheduledTask> ScheduledTasks
        {
            get
            {
                if ((this._ScheduledTasks == null))
                {
                    this._ScheduledTasks = base.CreateQuery<ScheduledTask>("ScheduledTasks");
                }
                return this._ScheduledTasks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ScheduledTask> _ScheduledTasks;
        /// <summary>
        /// There are no comments for Maps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Map> Maps
        {
            get
            {
                if ((this._Maps == null))
                {
                    this._Maps = base.CreateQuery<Map>("Maps");
                }
                return this._Maps;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Map> _Maps;
        /// <summary>
        /// There are no comments for MapPositions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MapPosition> MapPositions
        {
            get
            {
                if ((this._MapPositions == null))
                {
                    this._MapPositions = base.CreateQuery<MapPosition>("MapPositions");
                }
                return this._MapPositions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MapPosition> _MapPositions;
        /// <summary>
        /// There are no comments for Appointments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAppointments(Appointment appointment)
        {
            base.AddObject("Appointments", appointment);
        }
        /// <summary>
        /// There are no comments for ResponsibleSubjects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToResponsibleSubjects(ResponsibleSubject responsibleSubject)
        {
            base.AddObject("ResponsibleSubjects", responsibleSubject);
        }
        /// <summary>
        /// There are no comments for Series in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSeries(Series series)
        {
            base.AddObject("Series", series);
        }
        /// <summary>
        /// There are no comments for SeriesColors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSeriesColors(SeriesColor seriesColor)
        {
            base.AddObject("SeriesColors", seriesColor);
        }
        /// <summary>
        /// There are no comments for DayOfWeeks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDayOfWeeks(DayOfWeek dayOfWeek)
        {
            base.AddObject("DayOfWeeks", dayOfWeek);
        }
        /// <summary>
        /// There are no comments for ScheduledTasks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToScheduledTasks(ScheduledTask scheduledTask)
        {
            base.AddObject("ScheduledTasks", scheduledTask);
        }
        /// <summary>
        /// There are no comments for Maps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMaps(Map map)
        {
            base.AddObject("Maps", map);
        }
        /// <summary>
        /// There are no comments for MapPositions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMapPositions(MapPosition mapPosition)
        {
            base.AddObject("MapPositions", mapPosition);
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.Appointment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Appointments")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Appointment : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Appointment object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="begin">Initial value of Begin.</param>
        /// <param name="end">Initial value of End.</param>
        /// <param name="isAllDay">Initial value of IsAllDay.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Appointment CreateAppointment(int ID, global::System.DateTime begin, global::System.DateTime end, bool isAllDay)
        {
            Appointment appointment = new Appointment();
            appointment.Id = ID;
            appointment.Begin = begin;
            appointment.End = end;
            appointment.IsAllDay = isAllDay;
            return appointment;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Begin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Begin
        {
            get
            {
                return this._Begin;
            }
            set
            {
                this.OnBeginChanging(value);
                this._Begin = value;
                this.OnBeginChanged();
                this.OnPropertyChanged("Begin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Begin;
        partial void OnBeginChanging(global::System.DateTime value);
        partial void OnBeginChanged();
        /// <summary>
        /// There are no comments for Property End in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime End
        {
            get
            {
                return this._End;
            }
            set
            {
                this.OnEndChanging(value);
                this._End = value;
                this.OnEndChanged();
                this.OnPropertyChanged("End");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _End;
        partial void OnEndChanging(global::System.DateTime value);
        partial void OnEndChanged();
        /// <summary>
        /// There are no comments for Property IsAllDay in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsAllDay
        {
            get
            {
                return this._IsAllDay;
            }
            set
            {
                this.OnIsAllDayChanging(value);
                this._IsAllDay = value;
                this.OnIsAllDayChanged();
                this.OnPropertyChanged("IsAllDay");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsAllDay;
        partial void OnIsAllDayChanging(bool value);
        partial void OnIsAllDayChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.ResponsibleSubject in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ResponsibleSubjects")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public abstract partial class ResponsibleSubject : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.Employee in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Employee : ResponsibleSubject
    {
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Employee CreateEmployee(int ID)
        {
            Employee employee = new Employee();
            employee.Id = ID;
            return employee;
        }
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserName
        {
          get
          {
            return this._UserName;
          }
          set
          {
            this.OnUserNameChanging(value);
            this._UserName = value;
            this.OnUserNameChanged();
            this.OnPropertyChanged("UserName");
          }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
                this.OnPropertyChanged("Number");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Number;
        partial void OnNumberChanging(string value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Groups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<EmployeeGroup> Groups
        {
            get
            {
                return this._Groups;
            }
            set
            {
                this._Groups = value;
                this.OnPropertyChanged("Groups");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<EmployeeGroup> _Groups = new global::System.Data.Services.Client.DataServiceCollection<EmployeeGroup>(null, global::System.Data.Services.Client.TrackingMode.None);
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.EmployeeGroup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class EmployeeGroup : ResponsibleSubject
    {
        /// <summary>
        /// Create a new EmployeeGroup object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static EmployeeGroup CreateEmployeeGroup(int ID)
        {
            EmployeeGroup employeeGroup = new EmployeeGroup();
            employeeGroup.Id = ID;
            return employeeGroup;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.Series in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Series")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Series : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Series object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="begin">Initial value of Begin.</param>
        /// <param name="cycle">Initial value of Cycle.</param>
        /// <param name="end">Initial value of End.</param>
        /// <param name="endsWithDate">Initial value of EndsWithDate.</param>
        /// <param name="isAllDay">Initial value of IsAllDay.</param>
        /// <param name="isWeekdayRecurrence">Initial value of IsWeekdayRecurrence.</param>
        /// <param name="numberOfRecurrences">Initial value of NumberOfRecurrences.</param>
        /// <param name="recurrenceInterval">Initial value of RecurrenceInterval.</param>
        /// <param name="repeat">Initial value of Repeat.</param>
        /// <param name="repeatUntilDate">Initial value of RepeatUntilDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Series CreateSeries(int ID, global::System.DateTime begin, int cycle, global::System.DateTime end, bool endsWithDate, bool isAllDay, bool isWeekdayRecurrence, int numberOfRecurrences, int recurrenceInterval, bool repeat, global::System.DateTime repeatUntilDate)
        {
            Series series = new Series();
            series.Id = ID;
            series.Begin = begin;
            series.Cycle = cycle;
            series.End = end;
            series.EndsWithDate = endsWithDate;
            series.IsAllDay = isAllDay;
            series.IsWeekdayRecurrence = isWeekdayRecurrence;
            series.NumberOfRecurrences = numberOfRecurrences;
            series.RecurrenceInterval = recurrenceInterval;
            series.Repeat = repeat;
            series.RepeatUntilDate = repeatUntilDate;
            return series;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Begin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Begin
        {
            get
            {
                return this._Begin;
            }
            set
            {
                this.OnBeginChanging(value);
                this._Begin = value;
                this.OnBeginChanged();
                this.OnPropertyChanged("Begin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Begin;
        partial void OnBeginChanging(global::System.DateTime value);
        partial void OnBeginChanged();
        /// <summary>
        /// There are no comments for Property Cycle in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Cycle
        {
            get
            {
                return this._Cycle;
            }
            set
            {
                this.OnCycleChanging(value);
                this._Cycle = value;
                this.OnCycleChanged();
                this.OnPropertyChanged("Cycle");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Cycle;
        partial void OnCycleChanging(int value);
        partial void OnCycleChanged();
        /// <summary>
        /// There are no comments for Property End in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime End
        {
            get
            {
                return this._End;
            }
            set
            {
                this.OnEndChanging(value);
                this._End = value;
                this.OnEndChanged();
                this.OnPropertyChanged("End");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _End;
        partial void OnEndChanging(global::System.DateTime value);
        partial void OnEndChanged();
        /// <summary>
        /// There are no comments for Property EndsWithDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool EndsWithDate
        {
            get
            {
                return this._EndsWithDate;
            }
            set
            {
                this.OnEndsWithDateChanging(value);
                this._EndsWithDate = value;
                this.OnEndsWithDateChanged();
                this.OnPropertyChanged("EndsWithDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _EndsWithDate;
        partial void OnEndsWithDateChanging(bool value);
        partial void OnEndsWithDateChanged();
        /// <summary>
        /// There are no comments for Property IsAllDay in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsAllDay
        {
            get
            {
                return this._IsAllDay;
            }
            set
            {
                this.OnIsAllDayChanging(value);
                this._IsAllDay = value;
                this.OnIsAllDayChanged();
                this.OnPropertyChanged("IsAllDay");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsAllDay;
        partial void OnIsAllDayChanging(bool value);
        partial void OnIsAllDayChanged();
        /// <summary>
        /// There are no comments for Property IsWeekdayRecurrence in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsWeekdayRecurrence
        {
            get
            {
                return this._IsWeekdayRecurrence;
            }
            set
            {
                this.OnIsWeekdayRecurrenceChanging(value);
                this._IsWeekdayRecurrence = value;
                this.OnIsWeekdayRecurrenceChanged();
                this.OnPropertyChanged("IsWeekdayRecurrence");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsWeekdayRecurrence;
        partial void OnIsWeekdayRecurrenceChanging(bool value);
        partial void OnIsWeekdayRecurrenceChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property NumberOfRecurrences in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int NumberOfRecurrences
        {
            get
            {
                return this._NumberOfRecurrences;
            }
            set
            {
                this.OnNumberOfRecurrencesChanging(value);
                this._NumberOfRecurrences = value;
                this.OnNumberOfRecurrencesChanged();
                this.OnPropertyChanged("NumberOfRecurrences");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _NumberOfRecurrences;
        partial void OnNumberOfRecurrencesChanging(int value);
        partial void OnNumberOfRecurrencesChanged();
        /// <summary>
        /// There are no comments for Property RecurrenceInterval in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int RecurrenceInterval
        {
            get
            {
                return this._RecurrenceInterval;
            }
            set
            {
                this.OnRecurrenceIntervalChanging(value);
                this._RecurrenceInterval = value;
                this.OnRecurrenceIntervalChanged();
                this.OnPropertyChanged("RecurrenceInterval");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _RecurrenceInterval;
        partial void OnRecurrenceIntervalChanging(int value);
        partial void OnRecurrenceIntervalChanged();
        /// <summary>
        /// There are no comments for Property Repeat in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Repeat
        {
            get
            {
                return this._Repeat;
            }
            set
            {
                this.OnRepeatChanging(value);
                this._Repeat = value;
                this.OnRepeatChanged();
                this.OnPropertyChanged("Repeat");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Repeat;
        partial void OnRepeatChanging(bool value);
        partial void OnRepeatChanged();
        /// <summary>
        /// There are no comments for Property RepeatUntilDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime RepeatUntilDate
        {
            get
            {
                return this._RepeatUntilDate;
            }
            set
            {
                this.OnRepeatUntilDateChanging(value);
                this._RepeatUntilDate = value;
                this.OnRepeatUntilDateChanged();
                this.OnPropertyChanged("RepeatUntilDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _RepeatUntilDate;
        partial void OnRepeatUntilDateChanging(global::System.DateTime value);
        partial void OnRepeatUntilDateChanged();
        /// <summary>
        /// There are no comments for SeriesColor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SeriesColor SeriesColor
        {
            get
            {
                return this._SeriesColor;
            }
            set
            {
                this._SeriesColor = value;
                this.OnPropertyChanged("SeriesColor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private SeriesColor _SeriesColor;
        /// <summary>
        /// There are no comments for WeekDays in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<DayOfWeek> WeekDays
        {
            get
            {
                return this._WeekDays;
            }
            set
            {
                this._WeekDays = value;
                this.OnPropertyChanged("WeekDays");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<DayOfWeek> _WeekDays = new global::System.Data.Services.Client.DataServiceCollection<DayOfWeek>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.SeriesColor in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SeriesColors")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class SeriesColor : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SeriesColor object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="b">Initial value of B.</param>
        /// <param name="g">Initial value of G.</param>
        /// <param name="r">Initial value of R.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SeriesColor CreateSeriesColor(int ID, byte b, byte g, byte r)
        {
            SeriesColor seriesColor = new SeriesColor();
            seriesColor.Id = ID;
            seriesColor.B = b;
            seriesColor.G = g;
            seriesColor.R = r;
            return seriesColor;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property B in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte B
        {
            get
            {
                return this._B;
            }
            set
            {
                this.OnBChanging(value);
                this._B = value;
                this.OnBChanged();
                this.OnPropertyChanged("B");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte _B;
        partial void OnBChanging(byte value);
        partial void OnBChanged();
        /// <summary>
        /// There are no comments for Property G in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte G
        {
            get
            {
                return this._G;
            }
            set
            {
                this.OnGChanging(value);
                this._G = value;
                this.OnGChanged();
                this.OnPropertyChanged("G");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte _G;
        partial void OnGChanging(byte value);
        partial void OnGChanged();
        /// <summary>
        /// There are no comments for Property R in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte R
        {
            get
            {
                return this._R;
            }
            set
            {
                this.OnRChanging(value);
                this._R = value;
                this.OnRChanged();
                this.OnPropertyChanged("R");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte _R;
        partial void OnRChanging(byte value);
        partial void OnRChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.DayOfWeek in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DayOfWeeks")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class DayOfWeek : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DayOfWeek object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="weekDay">Initial value of WeekDay.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DayOfWeek CreateDayOfWeek(int ID, int weekDay)
        {
            DayOfWeek dayOfWeek = new DayOfWeek();
            dayOfWeek.Id = ID;
            dayOfWeek.WeekDay = weekDay;
            return dayOfWeek;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property WeekDay in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int WeekDay
        {
            get
            {
                return this._WeekDay;
            }
            set
            {
                this.OnWeekDayChanging(value);
                this._WeekDay = value;
                this.OnWeekDayChanged();
                this.OnPropertyChanged("WeekDay");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _WeekDay;
        partial void OnWeekDayChanging(int value);
        partial void OnWeekDayChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.ScheduledTask in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ScheduledTasks")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ScheduledTask : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ScheduledTask object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="progress">Initial value of Progress.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ScheduledTask CreateScheduledTask(int ID, float progress)
        {
            ScheduledTask scheduledTask = new ScheduledTask();
            scheduledTask.Id = ID;
            scheduledTask.Progress = progress;
            return scheduledTask;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Progress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float Progress
        {
            get
            {
                return this._Progress;
            }
            set
            {
                this.OnProgressChanging(value);
                this._Progress = value;
                this.OnProgressChanged();
                this.OnPropertyChanged("Progress");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _Progress;
        partial void OnProgressChanging(float value);
        partial void OnProgressChanged();
        /// <summary>
        /// There are no comments for AppointmentResponsibleSubject in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ResponsibleSubject AppointmentResponsibleSubject
        {
            get
            {
                return this._AppointmentResponsibleSubject;
            }
            set
            {
                this._AppointmentResponsibleSubject = value;
                this.OnPropertyChanged("AppointmentResponsibleSubject");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ResponsibleSubject _AppointmentResponsibleSubject;
        /// <summary>
        /// There are no comments for DueDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Appointment DueDate
        {
            get
            {
                return this._DueDate;
            }
            set
            {
                this._DueDate = value;
                this.OnPropertyChanged("DueDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Appointment _DueDate;
        /// <summary>
        /// There are no comments for EntryDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Appointment EntryDate
        {
            get
            {
                return this._EntryDate;
            }
            set
            {
                this._EntryDate = value;
                this.OnPropertyChanged("EntryDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Appointment _EntryDate;
        /// <summary>
        /// There are no comments for EntryResponsibleSubject in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ResponsibleSubject EntryResponsibleSubject
        {
            get
            {
                return this._EntryResponsibleSubject;
            }
            set
            {
                this._EntryResponsibleSubject = value;
                this.OnPropertyChanged("EntryResponsibleSubject");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ResponsibleSubject _EntryResponsibleSubject;
        /// <summary>
        /// There are no comments for RelatedSeries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Series RelatedSeries
        {
            get
            {
                return this._RelatedSeries;
            }
            set
            {
                this._RelatedSeries = value;
                this.OnPropertyChanged("RelatedSeries");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Series _RelatedSeries;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.Map in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Maps")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Map : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Map object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Map CreateMap(int ID)
        {
            Map map = new Map();
            map.Id = ID;
            return map;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property MapSource in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] MapSource
        {
            get
            {
                if ((this._MapSource != null))
                {
                    return ((byte[])(this._MapSource.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnMapSourceChanging(value);
                this._MapSource = value;
                this.OnMapSourceChanged();
                this.OnPropertyChanged("MapSource");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _MapSource;
        partial void OnMapSourceChanging(byte[] value);
        partial void OnMapSourceChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.MapPosition in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MapPositions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MapPosition : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MapPosition object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="xPosition">Initial value of XPosition.</param>
        /// <param name="yPosition">Initial value of YPosition.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MapPosition CreateMapPosition(int ID, double xPosition, double yPosition)
        {
            MapPosition mapPosition = new MapPosition();
            mapPosition.Id = ID;
            mapPosition.XPosition = xPosition;
            mapPosition.YPosition = yPosition;
            return mapPosition;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property XPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double XPosition
        {
            get
            {
                return this._XPosition;
            }
            set
            {
                this.OnXPositionChanging(value);
                this._XPosition = value;
                this.OnXPositionChanged();
                this.OnPropertyChanged("XPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _XPosition;
        partial void OnXPositionChanging(double value);
        partial void OnXPositionChanged();
        /// <summary>
        /// There are no comments for Property YPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double YPosition
        {
            get
            {
                return this._YPosition;
            }
            set
            {
                this.OnYPositionChanging(value);
                this._YPosition = value;
                this.OnYPositionChanged();
                this.OnPropertyChanged("YPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _YPosition;
        partial void OnYPositionChanging(double value);
        partial void OnYPositionChanged();
        /// <summary>
        /// There are no comments for Map in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Map Map
        {
            get
            {
                return this._Map;
            }
            set
            {
                this._Map = value;
                this.OnPropertyChanged("Map");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Map _Map;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
